{
 "title": "accidents_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Predict Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/predict\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Time (s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(inference_time_seconds_sum[5m]) / rate(inference_time_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"api:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Users",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM users LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Predictions",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(prediction) FROM predictions LIMIT 50 "
    }
   ]
  },
  {
   "title": "User Verified Predictions",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(user_verification) FROM predictions LIMIT 50 "
    }
   ]
  }
 ]
}