stages:
  import:
    cmd: python src/data/import_raw_data.py
    deps:
      - src/data/import_raw_data.py
      - src/data/check_structure.py
    outs:
      - data/raw/caracteristiques-2023.csv
      - data/raw/lieux-2023.csv
      - data/raw/usagers-2023.csv
      - data/raw/vehicules-2023.csv
  preprocess:
    cmd: python src/data/make_dataset.py
    deps:
      - data/raw/caracteristiques-2023.csv
      - data/raw/lieux-2023.csv
      - data/raw/usagers-2023.csv
      - data/raw/vehicules-2023.csv
      - src/data/make_dataset.py
    outs:
      - data/preprocessed/X_test.csv
      - data/preprocessed/X_train.csv
      - data/preprocessed/y_test.csv
      - data/preprocessed/y_train.csv
  train_rfc:
    cmd: python src/models/train_random_forests.py
    deps:
      - data/preprocessed/X_test.csv
      - data/preprocessed/X_train.csv
      - data/preprocessed/y_test.csv
      - data/preprocessed/y_train.csv
      - src/models/train_random_forests.py
    outs:
      - mlruns/RandomForests/
      - models/best_random_forests.joblib
    metrics:
      - metrics/RandomForests_scores.json