stages:
  import:
    cmd: python src/data/import_raw_data.py
    deps:
      - src/data/import_raw_data.py
      - src/data/check_structure.py
    outs:
      - data/raw/caracteristiques-2021.csv
      - data/raw/lieux-2021.csv
      - data/raw/usagers-2021.csv
      - data/raw/vehicules-2021.csv
  preprocess:
    cmd: python src/data/make_dataset.py
    deps:
      - data/raw/caracteristiques-2021.csv
      - data/raw/lieux-2021.csv
      - data/raw/usagers-2021.csv
      - data/raw/vehicules-2021.csv
    outs:
      - data/preprocessed/X_test.csv
      - data/preprocessed/X_train.csv
      - data/preprocessed/y_test.csv
      - data/preprocessed/y_train.csv
  train_rfc:
    cmd: python src/models/train_random_forests.py --version 1
    deps:
      - data/preprocessed/X_test.csv
      - data/preprocessed/X_train.csv
      - data/preprocessed/y_test.csv
      - data/preprocessed/y_train.csv
    outs:
      - mlruns/RandomForests_v1/
    metrics:
      - metrics/RandomForests_v1_scores.json