FROM python:3.9-slim

WORKDIR /app
COPY ./src/api/requirements.txt requirements.txt
COPY ./src/api/app.py app.py
COPY ./models/best_random_forests.joblib best_random_forests.joblib

RUN pip install -r requirements.txt

EXPOSE 8888

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8888"]
