FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements file
COPY src/data/requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy script and data
COPY src/data/simulate_data.py .  
COPY src/data/check_structure.py .
COPY src/data/make_dataset.py .

CMD ["python3", "simulate_data.py"]