# config file for prometheus

# global config
global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
      - alertmanager:9093
rule_files:
  - "alerting_rules.yml"
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus:9090
- job_name: 'fastapi'
  scrape_interval: 5s
  metrics_path: /metrics
  static_configs:
    - targets: ['api:8000']