global:
  smtp_from: "prometheus.datascientest@gmail.com"
  smtp_smarthost: "smtp.gmail.com:465"
  smtp_auth_username: "prometheus.datascientest@gmail.com"
  smtp_auth_password: "qsyhonvlraonufcg"
  smtp_require_tls: false

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: "default-receiver"

receivers:
  - name: "default-receiver"
    email_configs:
      - to: "prometheus.datascientest@gmail.com"
      - to: "dae.anneliese.schmidt@gmail.com" # change this
  - name: "admin"
    email_configs:
      - to: "prometheus.datascientest@gmail.com"