on:
  push:
    branches: [philjhowson]
  pull_request:
    branches: [philjhowson]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc
          pip install dvc-s3
          pip install ruff

      - name: Configure DVC
        run: |
          dvc remote add origin s3://dvc
          dvc remote modify origin endpointurl https://dagshub.com/philjhowson/MLOps_accidents.s3
          dvc remote modify origin --local access_key_id ${{ secrets.PHILJHOWSON_DVC_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.PHILJHOWSON_DVC_ACCESS_KEY }}

      - name: Run DVC Repro to Pull Data
        run: |
          dvc pull -r origin
          dvc repro

      - name: Run Ruff
        run: ruff check . --fix

      - name: Format with Ruff
        run: ruff format .
